version: "3.6"
services:
  # Master
  manager:
    image: "spruha29/spruha-thesis-repo1:v1.1"
    networks:
      - cluster-net
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  # Workers
  worker:
    image: "spruha29/spruha-thesis-repo1:v1.1"
    networks:
      - cluster-net
    ports:
      - 8081:8081
    deploy:
      mode: global
      placement:
        constraints:
          - node.role!=manager

# Uses host network
networks:
  cluster-net:
    name: host
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1280
